### ISSUE TITLE
Use JNetReflector to create as many classes as possible in JNet

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/JNet#130]
**Is your feature request related to a problem? Please describe.**
Java has many classes not reflected till now. JNetReflector seems enough mature and it is possible to use it to create gateway classes starting from the JARs of a generic JRE.

**Describe the solution you'd like**
Within the `lib` folder of a JRE there are the JARs of the Java SE classes, the main one is **rt.jar**. Within it there are the `.class` files usable to create the proxies, many classes are just available.
Since **rt.jar** is loaded from the JRE itself, it is not possible to add it in the Classpath like JNetReflector does now. So:
- add an option to avoid to insert the JARs in classpath, but leave them to be analyzed
- create a specific folder under JNet project to avoid to overwrite available files
- until now JNetReflector does not manage generation of classes to receive events, verify how to avoid to create standard gateway classes for events

About classes to be reflected: many namespace in **rt.jar** maybe are internal, after first test try to avoid usefulness namespaces.

Use, as reference, a Java 8 JRE for backward compatibility (the classes available till now was generated from that reference) and use the official Oracle Javadoc URL.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
About
> Use, as reference, a Java 8 JRE for backward compatibility (the classes available till now was generated from that reference) and use the official Oracle Javadoc URL.
Even if it is possible to use the rt.jar from Java SE 8, the execution can be done only on a Java SE 11+ and it can get the tool confused when the classes and Javadoc URLs will be generated; this mainly because:
- classes are found using the content of the **rt.jar** file set in command-line
- the reflection will be done using the runtime version available in the hosted JRE, but the minimum version supported from JCOBridge is Java SE 11
- newest JRE can have classes exposing more methods which needs classes not listed in the rt.jar of Java 8

**Comment by masesdevelopers** [comment]
About
> until now JNetReflector does not manage generation of classes to receive events, verify how to avoid to create standard gateway classes for events

some classes, which needs Java counterpart, ends with `Listener`. So in first instance if a class name ends with `Listener` the tool can avoid its reflection, but in general a tool like JNetReflector cannot distinguish which interface, or class, shall be managed in different way only because it represents a callback.

**Comment by masesdevelopers** [comment]
> the reflection will be done using the runtime version available in the hosted JRE, but the minimum version supported from JCOBridge is Java SE 11

JNet will be updated to use Java 11 since JCOBridge is not supported on previous platforms

> newest JRE can have classes exposing more methods which needs classes not listed in the rt.jar of Java 8

A new switch `ModulesToParse` will be added to list the modules that shall be reflected; since many classes maybe will be in conflict with .NET convention it will be added the `NamespacesInConflict` command line switch to list the namespace that must be changed: the namespace will be suffixed with an **Ns** string.

> So in first instance if a class name ends with `Listener` the tool can avoid its reflection, but in general a tool like JNetReflector cannot distinguish which interface, or class, shall be managed in different way only because it represents a callback.

The previous will be implemented checking if the the ends with `Listener` or `Adapter`, then will be added a command line switch `ClassesToBeListener` to list all classes which are events callback.

Other than this some operators will be added, to enabled class conversion in case of interfaces, and the format will be:

```c#
public static implicit operator DestinationType(OriginType t) => t.Cast<DestinationType>();
```

**Comment by mariomastrodicasa** [comment]
Looking into the generated documentation seems that:
- Operators miss references to the classes used: an help like **Converter from X to Y**, where X and Y are the links to the documentation
- Method help does not report the `parameter`, `return` and `exception` which can be retrieved as reference and inserted into documentation: adding the references within these fields better fills the empty fields in documentation; maybe this can be done only for non native types 

I open a specific low priority issue on this.

**Comment by masesdevelopers** [comment]
Update news section of README.md to inform on availability of Java 11 reflection

**Comment by mariomastrodicasa** [comment]
> Other than this, some operators will be added to enabled class conversion in case of interfaces, and the format will be:

@masesdevelopers looking in the code and in the Java 11 documentation it is possible to highlight some missing operators. An example is [BlockingQueue](https://github.com/masesgroup/JNet/blob/67e73be4df1dda9e92102b9511aaaf7fb4c56dfc/src/net/JNet/Generated/Java/Util/Concurrent/BlockingQueue.cs) which miss all operators.

Seems the filtering happens in:
https://github.com/masesgroup/JNet/blob/67e73be4df1dda9e92102b9511aaaf7fb4c56dfc/src/net/JNetReflector/InternalMethods.cs#L582
which filters generic types, however generic classes are no more filtered. 
The same filter is applies in:
https://github.com/masesgroup/JNet/blob/67e73be4df1dda9e92102b9511aaaf7fb4c56dfc/src/net/JNetReflector/InternalMethods.cs#L485
and
https://github.com/masesgroup/JNet/blob/67e73be4df1dda9e92102b9511aaaf7fb4c56dfc/src/net/JNetReflector/InternalMethods.cs#L643
and
https://github.com/masesgroup/JNet/blob/67e73be4df1dda9e92102b9511aaaf7fb4c56dfc/src/net/JNetReflector/InternalMethods.cs#L844
